### ISSUE TITLE
Invalid syntax

### ISSUE THREAD

**Issue by AlexandreAA1122** [TeaByte/telegram-views#18]
Hi guys,

Sorry I am a total newbie;

Would like to know the exact syntax to make the code run.

Or maybe the essential steps before running it

I keep having invalid syntax errors,

Thanks a lot,

Alexandre

**Comment by TeaByte** [comment]
the script takes Arguments just run it on the terminal with data

like:
tviews.py --mode auto --channel tviews --post 4

read the README.md
