### ISSUE TITLE
Run the script noothing happens 

### ISSUE THREAD

**Issue by HimerRokovoy** [TeaByte/telegram-views#21]
Dear Sir

I have a problem with running the script, I am trying to run the script from pycharm(cloned repo) with this command - 
./tviews.py -t https -m rotate -p login:4nF2cw@196.18.14.105:8000 -с Boost IT Studio -pt5
and after I run it the cmd window opens for an instant and then immediately disappears
I also tried to run run it from cmd on windows using the command on the picture, nothing happend as well
![image](https://github.com/TeaByte/telegram-views/assets/73633029/a3c2dab1-5e3c-4859-ba8d-c974850ce177)
I would be extremely grateful for your help

**Comment by HimerRokovoy** [comment]
thank you, tho script is running now, i really wonder what does this fields mean
![image](https://github.com/TeaByte/telegram-views/assets/73633029/17d51dda-c3d6-4415-b2a3-907c9caf858b)
'Sent'
'Fail'
Errors
Even though script is runnig but no views are growing, does the script take some time to increase the amount of views?

**Comment by TeaByte** [comment]
hmmm I see you are using a rotated proxy 
are you sure there is many IPs on that ?

**Comment by HimerRokovoy** [comment]
actually I have also tried another option auto scraping mode and the result is absolutelly the same -
the number of sents is growing but no views are coming

**Comment by HimerRokovoy** [comment]
I also want to try second option with loading proxies from file
what format shoud they be?

**Comment by TeaByte** [comment]
The **auto** mode is auto scrapping from the proxy sources in auto file 
The **file** mode just get list of proxies from a text file and loop on them
The **rotate** just do a while loop and rotating the proxy 

and no I don't speak Russian
