### ISSUE TITLE
Waiting...

### ISSUE THREAD

**Issue by MattTG01** [TeaByte/telegram-views#22]
Hey, Ive used the tool and it never gets past the Waiting... screen.
I have even used your channel and post id: python tviews.py --mode auto --channel tviews --post 4

Still the same issue. Any solutions?
Thanks in advance!

**Comment by Zergg279** [comment]
Same issue here - can't get around it

**Comment by TeaByte** [comment]
Stuck at waiting mean one of 3 things

1- invalid proxy 
2- invalid channel or post
3- bad network while trying to scrap proxies in auto mode

the script badly designed I should make it tell you with one of 3 things make you waiting 
I just made this script months ago didn't thought it will make it to 100+ starts
I will try to remake it soon with better ideas and code + more additions
